FROM tensorflow/tensorflow:latest-gpu

WORKDIR /app

COPY source dest

RUN apt-get update && \
    apt-get install -y \
    libgl1-mesa-glx \
    libgtk-3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install \
    opencv-python \
    tensorflow \
    scikit-learn \
    numba

EXPOSE 8000

CMD ["/bin/bash"]
